apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-api
  namespace: mi-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-api
  template:
    metadata:
      labels:
        app: mi-api
    spec:
      containers:
        - name: mi-api
          image: mi-api:v1
          imagePullPolicy: Never        # Usar imagen local cargada con kind load
          ports:
            - containerPort: 3000
          env:
            - name: APP_VERSION
              value: "v1"
          readinessProbe:               # Kubernetes comprueba si el pod está listo
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:                # Kubernetes reinicia el pod si deja de responder
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
